// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DIAGRAM;

/************************************************************/
/**
 * 
 */
public class AccountType {
	/**
	 * 
	 */
	public int atmno;
	/**
	 * 
	 */
	public int Accno;
	/**
	 * 
	 */
	public int pno;
	/**
	 * 
	 */
	public String acctype;
	/**
	 * 
	 */
	public String actypegive;
	/**
	 * 
	 */
	public TransactionMenu transactionmenu;
}
