// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DIAGRAM;

/************************************************************/
/**
 * 
 */
public class AtmCardno {
	/**
	 * 
	 */
	public int Accno;
	/**
	 * 
	 */
	public int atmno;
	/**
	 * 
	 */
	public int pno;
	/**
	 * 
	 */
	public AccountType accounttype;
}
