// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DIAGRAM;

/************************************************************/
/**
 * 
 */
public class CashWithdrawal {
	/**
	 * 
	 */
	public int pno;
	/**
	 * 
	 */
	public int atmno;
	/**
	 * 
	 */
	public int Accno;
	/**
	 * 
	 */
	public String acctype;
	/**
	 * 
	 */
	public String StartDate;
	/**
	 * 
	 */
	public float giv_am;
	/**
	 * 
	 */
	public float amt;
	/**
	 * 
	 */
	public float a_bal;
	/**
	 * 
	 */
	public float atm_min;
}
