// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package DIAGRAM;

/************************************************************/
/**
 * 
 */
public class TransactionMenu {
	/**
	 * 
	 */
	public String acctype;
	/**
	 * 
	 */
	public int atmno;
	/**
	 * 
	 */
	public int Accno;
}
